{% set version = '1.3.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-stringr
  version: {{ version|replace("-", "_") }}

source:
  fn: stringr_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/stringr_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/stringr/stringr_{{ version }}.tar.gz
  sha256: 23b048d2344cafa10a3480f8d52ab818525c6fdf7210290635f3a10de772bb1d

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-glue
    - r-magrittr
    - r-stringi >=1.1.6

  run:
    - r-base
    - r-glue
    - r-magrittr
    - r-stringi >=1.1.6

test:
  commands:
    - $R -e "library('stringr')"  # [not win]
    - "\"%R%\" -e \"library('stringr')\""  # [win]

about:
  home: https://github.com/hadley/stringr
  license: GPL-2
  summary: "A consistent, simple and easy to use set of wrappers around the fantastic 'stringi'
    package. All function and argument names (and positions) are consistent, all functions
    deal with NA's and zero length vectors in the same way, and the output from one
    function is easy to feed into the input of another."
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-2'  # [win]

extra:
  recipe-maintainers:
    - ocefpaf
    - cbrueffer
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
