{% set version = "1.5.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-stringr
  version: {{ version|replace("-", "_") }}

source:
  fn: stringr_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/stringr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/stringr/stringr_{{ version }}.tar.gz
  sha256: 52b159d7700a139111b4caf939e7c9c6ab3e01185181400d70a74c552826633a

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-glue >=1.2.0
    - r-magrittr
    - r-stringi >=1.1.7

  run:
    - r-base
    - r-glue >=1.2.0
    - r-magrittr
    - r-stringi >=1.1.7

test:
  commands:
    - $R -e "library('stringr')"           # [not win]
    - "\"%R%\" -e \"library('stringr')\""  # [win]

about:
  home: http://stringr.tidyverse.org, https://github.com/tidyverse/stringr
  license: GPL-2
  summary: A consistent, simple and easy to use set of wrappers around the fantastic 'stringi' package. All function and argument names (and positions) are consistent, all functions deal with "NA"'s and zero length vectors in the same way, and the output from one function is easy to feed into the input of another.
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2  # [unix]
  license_file: {{ environ["PREFIX"] }}\R\share\licenses\GPL-2  # [win]

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
