{% set version = '1.4.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-stringr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/stringr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/stringr/stringr_{{ version }}.tar.gz
  sha256: 87604d2d3a9ad8fd68444ce0865b59e2ffbdb548a38d6634796bbd83eeb931dd

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-glue >=1.2.0
    - r-magrittr
    - r-stringi >=1.1.7
  run:
    - r-base
    - r-glue >=1.2.0
    - r-magrittr
    - r-stringi >=1.1.7

test:
  commands:
    - $R -e "library('stringr')"           # [not win]
    - "\"%R%\" -e \"library('stringr')\""  # [win]

about:
  home: http://stringr.tidyverse.org, https://github.com/tidyverse/stringr
  license: GPL-2
  summary: A consistent, simple and easy to use set of wrappers around the fantastic 'stringi'
    package. All function and argument names (and positions) are consistent, all functions
    deal with "NA"'s and zero length vectors in the same way, and the output from one
    function is easy to feed into the input of another.
  license_family: GPL2

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
    - philip-khor

# Package: stringr
# Title: Simple, Consistent Wrappers for Common String Operations
# Version: 1.4.0
# Authors@R:  c(person(given = "Hadley", family = "Wickham", role = c("aut", "cre", "cph"), email = "hadley@rstudio.com"), person(given = "RStudio", role = c("cph", "fnd")))
# Description: A consistent, simple and easy to use set of wrappers around the fantastic 'stringi' package. All function and argument names (and positions) are consistent, all functions deal with "NA"'s and zero length vectors in the same way, and the output from one function is easy to feed into the input of another.
# License: GPL-2 | file LICENSE
# URL: http://stringr.tidyverse.org, https://github.com/tidyverse/stringr
# BugReports: https://github.com/tidyverse/stringr/issues
# Depends: R (>= 3.1)
# Imports: glue (>= 1.2.0), magrittr, stringi (>= 1.1.7)
# Suggests: covr, htmltools, htmlwidgets, knitr, rmarkdown, testthat
# VignetteBuilder: knitr
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-02-09 16:03:19 UTC; hadley
# Author: Hadley Wickham [aut, cre, cph], RStudio [cph, fnd]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-02-10 03:40:03 UTC
