appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: aoQj4a/GndXElx0Nn3tERZT5PKfGLw1QG0lomvl7I+pF4b6SKXqeIpnegOkhx0g4y2UHH588HCWaLDFwoSkpBoPNQEH8rXHIR1HcUYgscDF1RBGz90apmXCEXlxdRDa+isMFr7yghnW1H76/uKJcPLggT8ES7IYrL3U9IuAXXvL9CrEdP5MZ/zItB1Ytqn7RHVaxAXRE4LpEJYbVf3olAy4dXQWQlhl1Wnn/g6RvwQHRxzH4u6JZ0+qFMBGh9zB//i4LcgJGuAEq2IEFQReIUDc/4azmryj19j0yElve42W6XPRylkPvHQWCSN+YWTH+TBe7+9WZtvSQc0+jgf5x9g91seqjsVH0wn15bmtqw6cdOhPN8IkA/xCLxJoOv70/ZVRoA1G/SLrsFkh36B4hPXp6ojlEbR0ds9kaZ6njxCer29EhTV/UVco3HVqYfnCXPY0i0P7tjO47kC0srNCqeDqjHr6omteTFX4+OAVMBgAYLfTaIbofMOWc+SHvNNMo38oVrS438wemHeAQlrvp1KU0N4H8I5lbBpm5aCf3RKnki5q6ayZpQU44b9Ue91blUgknVFfEJgEl3W3z8l1wCc4ARpvrcn32qCaXPFpHMEYMz1FYNdx/ltRZhU+0PSPmMZY30WzejeB4qDRLxfZckOQ2PiNmW8aJlkjZj3RHfOY=}
